config/routes.rb
Treeview::Application.routes.draw do

  root :to => 'tree_views#index'

  resources :tree_views

end

app/models/tree_view.rb
class TreeView < ActiveRecord::Base
  attr_accessible :name
  attr_accessible :parent_id
  attr_accessible :ancestry
  has_ancestry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tree_views_controller.rb
class TreeViewsController < ApplicationController
  # GET /tree_views
  # GET /tree_views.json
  def index
    @tree_views = TreeView.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tree_views }
    end
  end

  # GET /tree_views/1
  # GET /tree_views/1.json
  def show
    @tree_view = TreeView.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tree_view }
    end
  end

  # GET /tree_views/new
  # GET /tree_views/new.json
  def new
    @tree_view = TreeView.new
    @tree_view.parent_id = params[:prev_node]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tree_view }
    end
  end

  # GET /tree_views/1/edit
  def edit
    @tree_view = TreeView.find(params[:id])
  end

  # POST /tree_views
  # POST /tree_views.json
  def create
    @tree_view = TreeView.new(params[:tree_view])
    puts('helllpkpokpoj=---------------------------------------------------------------------------------------')
    puts(params[:prev_node])
    respond_to do |format|
      if @tree_view.save
        format.html { redirect_to @tree_view, notice: 'Tree view was successfully created.' }
        format.json { render json: @tree_view, status: :created, location: @tree_view }
      else
        format.html { render action: "new" }
        format.json { render json: @tree_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tree_views/1
  # PUT /tree_views/1.json
  def update
    @tree_view = TreeView.find(params[:id])

    respond_to do |format|
      if @tree_view.update_attributes(params[:tree_view])
        format.html { redirect_to @tree_view, notice: 'Tree view was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tree_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tree_views/1
  # DELETE /tree_views/1.json
  def destroy
    @tree_view = TreeView.find(params[:id])
    @tree_view.destroy

    respond_to do |format|
      format.html { redirect_to tree_views_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tree_view_helper.rb
module TreeViewHelper
end

app/helpers/tree_views_helper.rb
module TreeViewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treeview</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tree_views/_form.html.erb
  
  <%= form_for(@tree_view) do |f| %>
    <% @tree_view.attributes.each do |attr_name, attr_value| %>
      <% if(attr_name != 'id' and attr_name != 'created_at' and attr_name != 'updated_at') %>
        <div class="field">
          <%= f.label attr_name %><br />
          <%= f.text_field  attr_name%>
        </div>
      <% end%>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

app/views/tree_views/edit.html.erb
<h1>Editing tree_view</h1>

<%= render 'form' %>

<%= link_to 'Show', @tree_view %> |
<%= link_to 'Back', tree_views_path %>

app/views/tree_views/index.html.erb
<h1>Tree View</h1>

<% @tree_views.each do |tree_view| %>
  <p class='indent'>
    <%= tree_view.name %>
    <%= link_to 'Show', tree_view %>
    <%= link_to 'Edit', edit_tree_view_path(tree_view) %>
    <%= link_to 'Destroy', tree_view, method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to "New with two new fields", {:controller => "tree_views", :action => "new", :prev_node => tree_view.id, :new_fields => 2}%>
  </p>
<% end %>

app/views/tree_views/new.html.erb
<h1>New tree_view</h1>

<%= render 'form' %>

<%= link_to 'Back', tree_views_path %>

app/views/tree_views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tree_view.name %>
</p>
<p>
  <b>Parent:</b>
  <%= @tree_view.parent_id %>
</p>



<%= link_to 'Edit', edit_tree_view_path(@tree_view) %> |
<%= link_to 'Back', tree_views_path %>